# fly.toml app configuration file generated for unitas on 2026-05-30T23:26:19+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'unitas'
primary_region = 'gru'

[build]
  dockerfile = 'Dockerfile.render'



[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
